version: "3"

services:
  arbiter:
    image: valoha/bot_arbiter
    ports:
      - "9443"
      - "80"
      - "5000"
      - "443"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: valoha/bot_db_postgres
    ports:
      - "5432"